name: Bump Plugin Version

on:
  push:
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest

    # Eksplicitno podesite permissions
    permissions:
      contents: write  # Dozvola za push

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Bump patch version
        run: |
          python -c "..."

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Bump pluginVersion after push to main'
          branch: main
          # Eksplicitno koristite GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}