- name: Bump patch version
  run: |
    echo "Current gradle.properties content:"
    cat gradle.properties
    echo ""

    python -c "
    import re
    path = 'gradle.properties'
    
    print(f'Reading file: {path}')
    with open(path) as f:
      lines = f.readlines()
      print('Original lines:', lines)
    
    for i, line in enumerate(lines):
      if line.strip().startswith('pluginVersion'):
        print(f'Found version line at index {i}: {line.strip()}')
        v = re.findall(r'(\d+)\.(\d+)\.(\d+)', line)[0]
        print(f'Current version: {v}')
        new = f'{v[0]}.{v[1]}.{int(v[2])+1}'
        lines[i] = f'pluginVersion = {new}\n'
        print(f'New version: {new}')
    
    print('Modified lines:', lines)
    with open(path, 'w') as f:
      f.writelines(lines)
    print('File updated successfully')
    "

    echo ""
    echo "Updated gradle.properties content:"
    cat gradle.properties